info:
    app:
        name: "agenda-de-lives"
        description: "Os shows são transmitidos ao vivo atraves das redes sociais em lives."
        version: v0.0.1

server:
    port: 4200

spring:
    h2:
        console:
            enabled: true
            path: /h2
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:live
        username: ADMINAPI
        password: PASSW0RD
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect